apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: log-collector
  labels:
    app: log-collector
rules:
  - apiGroups: [""]
    resources: ["pods/log", "pods"]
    verbs: ["get", "list"]
